export const MESSAGE = {
    NOT_USER: 'Sorry but this user doesn\'t exist',
    USER_DOES_NOT_HAVE_ADMINISTRATOR_RIGHTS: 'The user does not have administrator rights',
    USER_EXIST: 'User is already exists',
    CATEGORY_EXIST: 'Category is already exists',
    CITY_EXIST: 'City is already exists',
    CITY_NOT_EXIST: 'City is not exists',
    CITY_ADDRESS_EXIST: 'City address is already exists',
    CITY_ADDRESS_NAME_EXIST: 'City address name is already exists',
    PRODUCT_EXIST: 'Product is already exists',
    PRODUCT_INGREDIENT_EXIST: 'Product ingredient is already exists',
    PRODUCT_PHOTO_NOT_EXIST: 'Product photo is not provided',
    CATEGORY_PHOTO_NOT_EXIST: 'Category photo is not provided',
    NOT_CATEGORY: 'Sorry but this category doesn\'t exist',
    NOT_PRODUCT: 'Sorry but this product doesn\'t exist',
    USER_UPDATED: 'User updated',
    ID_NOT_EXIST: 'Id not exist',
    WRONG_EMAIL_OR_PASSWORD: 'Wrong email or password',
    UNAUTHORIZED: 'Unauthorized',
    NOT_TOKEN: 'Not token',
    TOKEN_NOT_VALID: 'Token not valid',
    LOGOUT_USER: 'Logout',
    TO_BIG_PHOTO_FILE: 'Photo file if to big',
    WRONG_FILE_FORMAT: 'Wrong file format',
};
