export const MESSAGE = {
    NOT_USER: 'Sorry but this user doesn\'t exist',
    USER_EXIST: 'User is already exists',
    CATEGORY_EXIST: 'Category is already exists',
    PRODUCT_EXIST: 'Product is already exists',
    NOT_CATEGORY: 'Sorry but this category doesn\'t exist',
    NOT_PRODUCT: 'Sorry but this product doesn\'t exist',
    USER_UPDATED: 'User updated',
    ID_NOT_EXIST: 'Id not exist',
    WRONG_EMAIL_OR_PASSWORD: 'Wrong email or password',
    UNAUTHORIZED: 'Unauthorized',
    NOT_TOKEN: 'Not token',
    TOKEN_NOT_VALID: 'Token not valid',
    LOGOUT_USER: 'Logout',
};
